name: Copy Dataset to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  copy-dataset:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Clone target repository
      run: git clone https://user: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@huggingface.co/datasets/your-username/udio_dataset target-repo

    - name: Fetch file list from source repository
      run: |
        mkdir -p source-repo
        cd source-repo
        wget --header="Authorization: Bearer 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" https://huggingface.co/datasets/blanchon/udio_dataset/raw/main?recursive=1 -O file_list.json
        cd ..

    - name: Download and push files
      run: |
        cd source-repo
        for file_url in $(jq -r '.tree[] | select(.type=="blob") | .path' file_list.json); do
          wget --header="Authorization: Bearer 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" https://huggingface.co/datasets/blanchon/udio_dataset/raw/main/$file_url -O ../target-repo/$file_url
          cd ../target-repo
          git add $file_url
          git commit -m "Add $file_url"
          cd ../source-repo
        done
        cd ../target-repo
        git push origin main
