name: Copy Dataset to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  copy-dataset:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Clone original dataset repository
      run: git clone https://user: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@huggingface.co/datasets/blanchon/udio_dataset original-dataset

    - name: Initialize new dataset repository
      run: |
        mkdir new-dataset
        cd new-dataset
        git init --bare

    - name: Push to new Hugging Face repository
      run: |
        cd original-dataset
        git remote add new-dataset ../new-dataset
        git push new-dataset --all
        cd ../new-dataset
        git remote add origin https://user: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@huggingface.co/datasets/FreddyE/udtf
        git push origin --all
