name: Copy Dataset to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  copy-dataset:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  

    - name: Configure Git LFS to skip smudge (do not download actual files)
      run: |
        git lfs install --skip-smudge

    - name: Shallow clone repository with LFS pointers
      run: git clone --depth 1 https://user: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@huggingface.co/datasets/blanchon/udio_dataset original-dataset

    - name: Push LFS pointers to new repository
      run: |
        cd original-dataset
        git remote set-url origin https://user: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@huggingface.co/datasets/FreddyE/udtf
        git push origin main

