name: Copy Dataset to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  copy-dataset:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Clone original dataset repository
      run: git clone --mirror https://user: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@huggingface.co/datasets/blanchon/udio_dataset udio_dataset

    - name: Push to new Hugging Face repository
      run: |
        cd udio_dataset
        git remote add new-dataset https://user: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@huggingface.co/datasets/FreddyE/udtf
        git push new-dataset --mirror
