name: Copy Dataset to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  copy-dataset:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: try hugcli
      run: |
        huggingface-cli --help
  

    - name: Configure Git LFS to skip smudge (do not download actual files)
      run: |
        git lfs install --skip-smudge

    - name: Disable LFS pre-push hook
      run: |
        git config --global lfs.skipdownload true
        git config --global lfs.skipverify true

    - name: clone repository with LFS pointers
      run: git clone https://user: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@huggingface.co/datasets/blanchon/udio_dataset original-dataset

    - name: Push LFS pointers to new repository
      run: |
        cd original-dataset
        git remote set-url origin https://user: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@huggingface.co/datasets/FreddyE/udtf
        git push origin main --force

